global:
  scrape_interval: 15s # Por defecto, recopila (hace scrape a) los objetivos cada 15 segundos.

scrape_configs:
  # El nombre del trabajo se añade como una etiqueta `job=<job_name>` a cualquier serie temporal recopilada desde esta configuración.
  - job_name: "prometheus"

    # Sobrescribe el valor predeterminado global y recopila objetivos de este trabajo cada 5 segundos.
    scrape_interval: 5s

    static_configs:
      - targets: ["localhost:9090"]
