openapi: 3.0.0
info:
  title: MS Tutorias API
  version: 1.0.0
  description: API del microservicio de tutorías universitarias.

servers:
  - url: http://localhost:3000/api

paths:
  /tutorias:
    get:
      summary: Obtener todas las tutorías
      tags:
        - Tutorías
      responses:
        "200":
          description: Lista de tutorías retornada correctamente
